# Generated by Django 3.0.3 on 2020-05-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_messagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageModel',
        ),
    ]
