# Generated by Django 3.0.3 on 2020-05-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_messagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageModel',
        ),
    ]
